# Ansible Inventory File for Medicure Continuous Deployment
# This defines the target hosts where our application will be deployed.

[webservers]
localhost ansible_connection=local

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
project_src=/home/shivam/Downloads/SEM1/MedicureEnhanced/medicure
deploy_dest=/opt/medicure
